import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Plus, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Empty, Page } from "@/components/iga/Page";
import { StatusBadge } from "@/components/iga/StatusBadge";
import { canOperate, formatDate, priorities, ticketStatuses } from "@/lib/iga";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/tickets")({head:()=>({meta:[{title:"Chamados — IGA Service"},{name:"description",content:"Gestão operacional de chamados técnicos."},{property:"og:title",content:"Chamados — IGA Service"},{property:"og:description",content:"Gestão operacional de chamados técnicos."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Tickets});
function Tickets(){
 const {user,role}=Route.useRouteContext();const can=canOperate(role);const [rows,setRows]=useState<any[]>([]);const [companies,setCompanies]=useState<any[]>([]);const [contacts,setContacts]=useState<any[]>([]);const [cats,setCats]=useState<any[]>([]);const [technicians,setTechnicians]=useState<any[]>([]);const [open,setOpen]=useState(false);const [q,setQ]=useState("");const [company,setCompany]=useState("");const [category,setCategory]=useState("");const [statusFilter,setStatusFilter]=useState("");const [priorityFilter,setPriorityFilter]=useState("");const [companyFilter,setCompanyFilter]=useState("");const [technicianFilter,setTechnicianFilter]=useState("");
 async function load(){const [{data:t},{data:c},{data:co},{data:ca},{data:te}]=await Promise.all([supabase.from("tickets").select("id,number,subject,status,priority,opened_at,company_id,assigned_technician_id,companies(trade_name),technicians(name)").order("opened_at",{ascending:false}),supabase.from("companies").select("id,trade_name").eq("status","active").order("trade_name"),supabase.from("contacts").select("id,name,company_id,phone").eq("status","active").order("name"),supabase.from("ticket_categories").select("id,name,parent_id").eq("status","active").order("name"),supabase.from("technicians").select("id,name").eq("status","active").order("name")]);setRows(t??[]);setCompanies(c??[]);setContacts(co??[]);setCats(ca??[]);setTechnicians(te??[])}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())&&(!statusFilter||r.status===statusFilter)&&(!priorityFilter||r.priority===priorityFilter)&&(!companyFilter||r.company_id===companyFilter)&&(!technicianFilter||r.assigned_technician_id===technicianFilter)),[rows,q,statusFilter,priorityFilter,companyFilter,technicianFilter]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const contact=contacts.find(x=>x.id===f.get("contact_id"));const sub=String(f.get("subcategory_id")||"");const {error}=await supabase.from("tickets").insert({company_id:String(f.get("company_id")),contact_id:String(f.get("contact_id")),requester_phone:contact?.phone||null,category_id:String(f.get("category_id"))||null,subcategory_id:sub||null,subject:String(f.get("subject")),description:String(f.get("description")),priority:String(f.get("priority")) as any,channel:"manual",created_by:user.id} as never);if(error){toast.error(error.message);return;}toast.success("Chamado aberto.");setOpen(false);setCompany("");setCategory("");await load()}
 return <Page title="Chamados" description="Acompanhe e conduza o atendimento técnico." action={can?<Button onClick={()=>setOpen(true)}><Plus/>Novo chamado</Button>:undefined}>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Abrir chamado manual</DialogTitle><DialogDescription>Registre a solicitação inicial do cliente.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><div><Label>Empresa / Cliente</Label><select className="form-control" name="company_id" required value={company} onChange={e=>setCompany(e.target.value)}><option value="">Selecione</option>{companies.map(x=><option key={x.id} value={x.id}>{x.trade_name}</option>)}</select></div><div><Label>Contato solicitante</Label><select key={company} className="form-control" name="contact_id" required><option value="">Selecione</option>{contacts.filter(x=>x.company_id===company).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><Label>Categoria</Label><select className="form-control" name="category_id" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Selecione</option>{cats.filter(x=>!x.parent_id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><Label>Subcategoria</Label><select key={category} className="form-control" name="subcategory_id" disabled={!category}><option value="">Selecione</option>{cats.filter(x=>x.parent_id===category).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="sm:col-span-2"><Label>Assunto</Label><Input name="subject" required/></div><div><Label>Prioridade</Label><select className="form-control" name="priority">{priorities.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div><Label>Canal</Label><Input value="Manual" disabled/></div><div className="sm:col-span-2"><Label>Descrição</Label><Textarea name="description" required rows={5}/></div><div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button>Abrir chamado</Button></div></form></DialogContent></Dialog>
 <div className="grid gap-3 lg:grid-cols-[minmax(15rem,1fr)_repeat(4,minmax(9rem,.55fr))]"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Pesquisar por número, assunto ou cliente..." value={q} onChange={e=>setQ(e.target.value)}/></div><Filter label="Status" value={statusFilter} onChange={setStatusFilter} options={ticketStatuses}/><Filter label="Prioridade" value={priorityFilter} onChange={setPriorityFilter} options={priorities}/><Filter label="Técnico" value={technicianFilter} onChange={setTechnicianFilter} options={technicians.map(x=>[x.id,x.name] as const)}/><Filter label="Empresa" value={companyFilter} onChange={setCompanyFilter} options={companies.map(x=>[x.id,x.trade_name] as const)}/></div>
 {filtered.length===0?<Empty>Nenhum chamado encontrado.</Empty>:<div className="overflow-hidden rounded-md border bg-card"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/60 text-left"><tr><th className="px-4 py-3">Número</th><th className="px-4 py-3">Assunto</th><th className="px-4 py-3">Cliente</th><th className="px-4 py-3">Técnico</th><th className="px-4 py-3">Prioridade</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Abertura</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t hover:bg-muted/30"><td className="px-4 py-3"><Link to="/tickets/$ticketId" params={{ticketId:r.id}} className="font-semibold text-primary hover:underline">{r.number}</Link></td><td className="px-4 py-3">{r.subject}</td><td className="px-4 py-3 text-muted-foreground">{r.companies?.trade_name}</td><td className="px-4 py-3 text-muted-foreground">{r.technicians?.name||"—"}</td><td className="px-4 py-3"><StatusBadge value={r.priority} kind="priority"/></td><td className="px-4 py-3"><StatusBadge value={r.status}/></td><td className="px-4 py-3 text-muted-foreground">{formatDate(r.opened_at)}</td></tr>)}</tbody></table></div></div>}</Page>}
function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:readonly (readonly [string,string])[]}){return <select aria-label={label} className="form-control" value={value} onChange={e=>onChange(e.target.value)}><option value="">{label}: todos</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
