import { useEffect, useMemo, useState } from "react";
import { Plus, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button"; import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger } from "@/components/ui/dialog"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Textarea } from "@/components/ui/textarea"; import { supabase } from "@/integrations/supabase/client"; import { errorMessage } from "@/lib/iga"; import { Empty, Page } from "./Page"; import { StatusBadge } from "./StatusBadge";
type Kind="companies"|"contacts"|"technicians"|"categories";
const config={companies:{title:"Empresas / Clientes",desc:"Cadastre e mantenha os clientes atendidos.",name:"trade_name",table:"companies"},contacts:{title:"Contatos",desc:"Gerencie solicitantes vinculados às empresas.",name:"name",table:"contacts"},technicians:{title:"Técnicos",desc:"Organize a equipe técnica vinculada aos usuários.",name:"name",table:"technicians"},categories:{title:"Categorias de Chamados",desc:"Estruture categorias e subcategorias do atendimento.",name:"name",table:"ticket_categories"}} as const;
export function ResourcePage({kind,userId,canManage}:{kind:Kind;userId:string;canManage:boolean}){const c=config[kind]; const [rows,setRows]=useState<any[]>([]); const [related,setRelated]=useState<any[]>([]); const [q,setQ]=useState(""); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false);
 async function load(){const {data,error}=await supabase.from(c.table).select("*").order(c.name); if(error) toast.error(error.message); else setRows(data??[]); if(kind==="contacts"){const r=await supabase.from("companies").select("id,trade_name").eq("status","active").order("trade_name");setRelated(r.data??[])} if(kind==="technicians"){const r=await supabase.from("profiles").select("id,full_name").order("full_name");setRelated(r.data??[])} if(kind==="categories"){const r=await supabase.from("ticket_categories").select("id,name").is("parent_id",null).order("name");setRelated(r.data??[])}}
 useEffect(()=>{void load()},[kind]); const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const fd=new FormData(e.currentTarget);let payload:any={};if(kind==="companies")payload={legal_name:fd.get("legal_name"),trade_name:fd.get("trade_name"),tax_id:fd.get("tax_id"),phone:fd.get("phone")||null,whatsapp:fd.get("whatsapp")||null,email:fd.get("email")||null,postal_code:fd.get("postal_code")||null,address:fd.get("address")||null,address_number:fd.get("address_number")||null,complement:fd.get("complement")||null,district:fd.get("district")||null,city:fd.get("city")||null,state:fd.get("state")||null,notes:fd.get("notes")||null,status:fd.get("status"),created_by:userId};if(kind==="contacts")payload={company_id:fd.get("company_id"),name:fd.get("name"),job_title:fd.get("job_title")||null,phone:fd.get("phone")||null,whatsapp:fd.get("whatsapp")||null,email:fd.get("email")||null,is_primary:fd.get("is_primary")==="on",status:fd.get("status"),created_by:userId};if(kind==="technicians")payload={user_id:fd.get("user_id"),name:fd.get("name"),phone:fd.get("phone")||null,email:fd.get("email"),specialty:fd.get("specialty")||null,status:fd.get("status")};if(kind==="categories")payload={name:fd.get("name"),parent_id:fd.get("parent_id")||null,status:fd.get("status")};const {error}=await supabase.from(c.table).insert(payload as never);setSaving(false);if(error)return toast.error(errorMessage(error));toast.success("Cadastro salvo com sucesso.");setOpen(false);await load()}
 return <Page title={c.title} description={c.desc} action={canManage?<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus/>Novo cadastro</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Novo cadastro</DialogTitle><DialogDescription>Preencha os dados obrigatórios.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">
 {kind==="companies"&&<><Field n="legal_name" l="Razão Social"/><Field n="trade_name" l="Nome Fantasia"/><Field n="tax_id" l="CNPJ/CPF"/><Field n="phone" l="Telefone" req={false}/><Field n="whatsapp" l="WhatsApp" req={false}/><Field n="email" l="E-mail" type="email" req={false}/><Field n="postal_code" l="CEP" req={false}/><Field n="address" l="Endereço" req={false}/><Field n="address_number" l="Número" req={false}/><Field n="complement" l="Complemento" req={false}/><Field n="district" l="Bairro" req={false}/><Field n="city" l="Cidade" req={false}/><Field n="state" l="UF" req={false}/><div className="sm:col-span-2"><Label>Observações</Label><Textarea name="notes"/></div></>}
 {kind==="contacts"&&<><SelectField n="company_id" l="Empresa / Cliente" rows={related}/><Field n="name" l="Nome"/><Field n="job_title" l="Cargo / Função" req={false}/><Field n="phone" l="Telefone" req={false}/><Field n="whatsapp" l="WhatsApp" req={false}/><Field n="email" l="E-mail" type="email" req={false}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="is_primary"/>Contato principal</label></>}
 {kind==="technicians"&&<><SelectField n="user_id" l="Usuário vinculado" rows={related}/><Field n="name" l="Nome"/><Field n="phone" l="Telefone" req={false}/><Field n="email" l="E-mail" type="email"/><Field n="specialty" l="Especialidade" req={false}/></>}
 {kind==="categories"&&<><Field n="name" l="Nome"/><SelectField n="parent_id" l="Categoria superior (opcional)" rows={related} optional/></>}
 <div><Label>Status</Label><select name="status" className="form-control"><option value="active">Ativo</option><option value="inactive">Inativo</option></select></div><div className="flex items-end justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={saving}>{saving?"Salvando...":"Salvar"}</Button></div></form></DialogContent></Dialog>:undefined}>
 <div className="relative max-w-md"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Pesquisar..." value={q} onChange={e=>setQ(e.target.value)}/></div>{filtered.length===0?<Empty>Nenhum cadastro encontrado.</Empty>:<div className="overflow-hidden rounded-md border bg-card"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/60 text-left"><tr><th className="px-4 py-3">Nome</th><th className="px-4 py-3">Detalhe</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t"><td className="px-4 py-3 font-medium">{r[c.name]}</td><td className="px-4 py-3 text-muted-foreground">{r.legal_name||r.email||(r.parent_id?"Subcategoria":"Categoria")||"—"}</td><td className="px-4 py-3"><StatusBadge value={r.status} kind="record"/></td></tr>)}</tbody></table></div></div>}</Page>}
function Field({n,l,type="text",req=true}:{n:string;l:string;type?:string;req?:boolean}){return <div><Label htmlFor={n}>{l}</Label><Input id={n} name={n} type={type} required={req}/></div>};function SelectField({n,l,rows,optional=false}:{n:string;l:string;rows:any[];optional?:boolean}){return <div><Label>{l}</Label><select name={n} required={!optional} className="form-control"><option value="">Selecione</option>{rows.map(r=><option key={r.id} value={r.id}>{r.trade_name||r.full_name||r.name}</option>)}</select></div>}
